export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const ERROR_FETCH_PRODUCTS = 'ERROR_FETCH_PRODUCTS';
export const ERROR_ADD_PRODUCT = 'ERROR_ADD_PRODUCT';
export const ERROR_EDIT_PRODUCT = 'ERROR_EDIT_PRODUCT';
export const ERROR_REMOVE_PRODUCT = 'ERROR_REMOVE_PRODUCT';